### ISSUE TITLE
About grf-encryption

### ISSUE THREAD

**Issue by carloshenrq** [Tokeiburu/GRFEditor#10]
Hi @Tokeiburu , how are you?

I've installed the version 1.8.7.3

<img width="542" alt="image" src="https://github.com/Tokeiburu/GRFEditor/assets/5216299/7dcca614-d4ea-4ed5-a254-7dfa4b80ef38">

And we have got an option for custom encryption.
Tools -> Settings -> Applications -> Encryption method

It loads an external GRF to encrypt. 
<img width="542" alt="image" src="https://github.com/Tokeiburu/GRFEditor/assets/5216299/fe41cb1c-a95e-48d8-8954-1ba385503d30">

So.., my question is... Is there any support file about what export methods this dll must have, vc++ version, etc...?
Thank you very much

**Comment by Tokeiburu** [comment]
Please refer to this post:
https://rathena.org/board/topic/77080-grf-grf-editor/?do=findComment&comment=432591
