### ISSUE TITLE
cannot work

### ISSUE THREAD

**Issue by konomicon** [Tokeiburu/GRFEditor#11]
Japanese RO
after 240917 update，GRF Editor cannot work
![240917-1](https://github.com/user-attachments/assets/c9dcf561-f813-435e-9c61-68e8f693ca46)
![240917-2](https://github.com/user-attachments/assets/d943f88d-7ac3-4a78-82ac-1229a8b1236c)

**Comment by Tatacho** [comment]
Same issue here. Was there any solution?

**Comment by konomicon** [comment]
Already solved in the forum，thank you

Tatacho ***@***.***> 于 2024年10月23日周三 11:19写道：

**Comment by Tatacho** [comment]
What was the solution though?

**Comment by Tokeiburu** [comment]
> What was the solution though?

I'm not very active on github; jRO released a new GRF format which I've added support in the latest version of GRF Editor. Though I've seen your new issue and that will require the full jRO GRF for me to have a look.
