### ISSUE TITLE
Unable to open jRO's data.grf

### ISSUE THREAD

**Issue by Tatacho** [Tokeiburu/GRFEditor#12]
Version: 1.8.7.8

2022 Visual C++ Redistributable is installed and the jRO header is enabled by default.

![grferror](https://github.com/user-attachments/assets/ba094f4a-0b47-4704-891d-9e38f526a8d8)

**Comment by Tokeiburu** [comment]
That's weird, this looks like another format yet again...? You'd have to upload the GRF somewhere for me to have a look at it.

**Comment by Tatacho** [comment]
https://mega.nz/file/2ZAEgLiC#MWLst9xMC_6TNLgNcyzvHs1XDyk226X34XjWFPs-An0

There you go. It's just the current updated jRO.

**Comment by Tokeiburu** [comment]
Thank you and sorry for the trouble (I'm unable to download jRO's official client/GRF).

I've updated to 1.8.8.1 : https://www.mediafire.com/file/aflylbhblrzpz0h

This new format allows GRF sizes bigger than 4GB and that's where the issues came from.
