### ISSUE TITLE
how to use this?

### ISSUE THREAD

**Issue by dnplnkton21** [Tokeiburu/GRFEditor#5]
im sorry im new here. please tell me how to use this? i really need the gutter line

**Comment by Tokeiburu** [comment]
Huh, you're... in the wrong place for this. If you're asking for support, please use the GRF Editor thread on rAthena:
- https://rathena.org/board/topic/77080-grf-grf-editor/

As for your question, Tools > Flat maps maker > Options > Show gutter lines.
