### ISSUE TITLE
GRF.dll

### ISSUE THREAD

**Issue by bernardomendes-bmcoder** [Tokeiburu/GRFEditor#6]
Hello my friend, I really like your work, I would like to know the functions present in GRF.dll, is it possible to know?

**Comment by Tokeiburu** [comment]
Heya,

I updated the readme file:
https://github.com/Tokeiburu/GRFEditor/tree/main#readme

It should be a good enough start. If that's not enough, you can also look into the ExampleProject which is more complete but also very old:
https://github.com/Tokeiburu/GRFEditor/blob/main/ExampleProject/Form1.cs
