### ISSUE TITLE
Garments being detected as "Orphan" files

### ISSUE THREAD

**Issue by relzz-v0** [Tokeiburu/GRFEditor#8]
I was cleaning the kRO Folder and I noticed most of the errors (like 98%) was due to orphan .ACT files on the Garments folder

Is there anything that can be done about this?

**Comment by Tokeiburu** [comment]
Well there is actually nothing wrong with missing spr files for garments. If you're referring to the Grf validation tool, you could uncheck "Missing corresponding Act or Spr files". Though you're right, I should exclude the garment folder. I'll apply the change on the next update.
